"""v4.1

Revision ID: 29d8154679d3
Revises: 57cc4861ad71
Create Date: 2021-02-15 12:01:45.516852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d8154679d3'
down_revision = '57cc4861ad71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_hole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holenum', sa.Integer(), nullable=True),
    sa.Column('holepar', sa.Integer(), nullable=True),
    sa.Column('holelength', sa.Integer(), nullable=True),
    sa.Column('holecourse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['holecourse_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holenum', 'holecourse_id')
    )
    op.create_index(op.f('ix_course_hole_holenum'), 'course_hole', ['holenum'], unique=False)
    op.drop_index('ix_hole_holenum', table_name='hole')
    op.drop_table('hole')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hole',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('holenum', sa.INTEGER(), nullable=True),
    sa.Column('holepar', sa.INTEGER(), nullable=True),
    sa.Column('holelength', sa.INTEGER(), nullable=True),
    sa.Column('holecourse_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['holecourse_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hole_holenum', 'hole', ['holenum'], unique=False)
    op.drop_index(op.f('ix_course_hole_holenum'), table_name='course_hole')
    op.drop_table('course_hole')
    # ### end Alembic commands ###
