"""v4

Revision ID: 57cc4861ad71
Revises: 665c17f7ecf0
Create Date: 2021-02-15 11:46:48.852377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57cc4861ad71'
down_revision = '665c17f7ecf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('round_hole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hole', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('ob', sa.Boolean(), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hole', 'round_id')
    )
    op.drop_table('roundscore')
    op.drop_index('ix_round_rounddate', table_name='round')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_round_rounddate', 'round', ['rounddate'], unique=False)
    op.create_table('roundscore',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hole', sa.INTEGER(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('round_id', sa.INTEGER(), nullable=True),
    sa.Column('ob', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('round_hole')
    # ### end Alembic commands ###
