"""v1.3.2

Revision ID: 665c17f7ecf0
Revises: a0c050c9e8f8
Create Date: 2021-01-31 11:01:24.423119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665c17f7ecf0'
down_revision = 'a0c050c9e8f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roundscore', sa.Column('ob', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roundscore', 'ob')
    # ### end Alembic commands ###
