"""v1 database

Revision ID: 851a00a0b178
Revises: 51fb56761300
Create Date: 2021-01-26 15:44:12.788904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851a00a0b178'
down_revision = '51fb56761300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coursename', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_coursename'), 'course', ['coursename'], unique=True)
    op.create_table('hole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holenum', sa.Integer(), nullable=True),
    sa.Column('holepar', sa.Integer(), nullable=True),
    sa.Column('holelength', sa.Integer(), nullable=True),
    sa.Column('holecourse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['holecourse_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hole_holenum'), 'hole', ['holenum'], unique=False)
    op.create_table('round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rounddate', sa.DateTime(), nullable=True),
    sa.Column('roundweather', sa.String(length=16), nullable=True),
    sa.Column('rounduser_id', sa.Integer(), nullable=True),
    sa.Column('roundcourse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roundcourse_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['rounduser_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_round_rounddate'), 'round', ['rounddate'], unique=False)
    op.create_table('roundscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hole', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roundscore')
    op.drop_index(op.f('ix_round_rounddate'), table_name='round')
    op.drop_table('round')
    op.drop_index(op.f('ix_hole_holenum'), table_name='hole')
    op.drop_table('hole')
    op.drop_index(op.f('ix_course_coursename'), table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###
